"""Change bonus from int to str

Revision ID: 285d798f0fb0
Revises: 5529002f22bf
Create Date: 2025-03-02 22:30:50.099494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285d798f0fb0'
down_revision = '5529002f22bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('bonus',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('bonus',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
