"""changed extra bonus to bonus plus three

Revision ID: 32fee5187661
Revises: f80fc475bec7
Create Date: 2025-03-04 22:31:12.108063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32fee5187661'
down_revision = 'f80fc475bec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_plus_three', sa.Boolean(), nullable=True))
        batch_op.drop_column('bonus_extra_roll')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_extra_roll', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('bonus_plus_three')

    # ### end Alembic commands ###
