"""Added completed to CorrectCode and removed from CorrectSentence

Revision ID: 49b5ba005eb0
Revises: 8b33f1ead209
Create Date: 2025-03-11 21:10:59.018855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b5ba005eb0'
down_revision = '8b33f1ead209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correct_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('correct_sentences', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correct_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('correct_codes', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
