"""Added displayed to PlayerSentence

Revision ID: 600366923241
Revises: d95797859898
Create Date: 2025-03-06 20:37:32.096787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600366923241'
down_revision = 'd95797859898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('displayed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_sentences', schema=None) as batch_op:
        batch_op.drop_column('displayed')

    # ### end Alembic commands ###
