"""Add completed field to CorrectSentence

Revision ID: 66c515ee9191
Revises: 32fee5187661
Create Date: 2025-03-05 21:06:30.660864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c515ee9191'
down_revision = '32fee5187661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correct_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correct_sentences', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
