"""Added PlayerNotification

Revision ID: 751467d0a290
Revises: c7fd5ee71deb
Create Date: 2025-03-06 21:10:47.027740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751467d0a290'
down_revision = 'c7fd5ee71deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_notifications')
    # ### end Alembic commands ###
