"""Add classrooms to CorrectSentence model

Revision ID: 8b33f1ead209
Revises: 751467d0a290
Create Date: 2025-03-10 21:52:41.745439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b33f1ead209'
down_revision = '751467d0a290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_correct_sentences')
    with op.batch_alter_table('correct_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_4th_grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('classroom_5th_grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('classroom_6th_grade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('classroom_7th_grade', sa.String(length=50), nullable=True))
        batch_op.drop_column('classroom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correct_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('classroom_7th_grade')
        batch_op.drop_column('classroom_6th_grade')
        batch_op.drop_column('classroom_5th_grade')
        batch_op.drop_column('classroom_4th_grade')

    op.create_table('_alembic_tmp_correct_sentences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('correct_sentence', sa.VARCHAR(length=255), nullable=False),
    sa.Column('cell_number', sa.INTEGER(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('classroom_4th_grade', sa.VARCHAR(length=50), nullable=False),
    sa.Column('classroom_5th_grade', sa.VARCHAR(length=50), nullable=False),
    sa.Column('classroom_6th_grade', sa.VARCHAR(length=50), nullable=False),
    sa.Column('classroom_7th_grade', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
