"""changed character limit

Revision ID: ac6ddac4a00f
Revises: 285d798f0fb0
Create Date: 2025-03-03 19:23:15.060665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6ddac4a00f'
down_revision = '285d798f0fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('bonus',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=254),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('bonus',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
