"""Added roll_displayed to PlayerCode and removed from PlayerSentence

Revision ID: c7fd5ee71deb
Revises: 600366923241
Create Date: 2025-03-06 20:40:33.876671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7fd5ee71deb'
down_revision = '600366923241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('displayed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('player_sentences', schema=None) as batch_op:
        batch_op.drop_column('displayed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('displayed', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('player_codes', schema=None) as batch_op:
        batch_op.drop_column('displayed')

    # ### end Alembic commands ###
