"""Initial migration

Revision ID: cc006818849a
Revises: 
Create Date: 2025-03-06 20:14:40.710523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc006818849a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correct_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('bonus_type', sa.String(length=255), nullable=False),
    sa.Column('sentence', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correct_sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correct_sentence', sa.String(length=255), nullable=False),
    sa.Column('cell_number', sa.Integer(), nullable=False),
    sa.Column('classroom', sa.String(length=50), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('bonus_plus_one', sa.Boolean(), nullable=True),
    sa.Column('bonus_plus_two', sa.Boolean(), nullable=True),
    sa.Column('bonus_plus_three', sa.Boolean(), nullable=True),
    sa.Column('task_done', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('shape', sa.String(length=20), nullable=False),
    sa.Column('roll_disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_status', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_tasks')
    op.drop_table('player_sentences')
    op.drop_table('player_codes')
    op.drop_table('players')
    op.drop_table('correct_sentences')
    op.drop_table('correct_codes')
    # ### end Alembic commands ###
