"""splited bonus columns into 3

Revision ID: cdb1a5322408
Revises: ac6ddac4a00f
Create Date: 2025-03-03 22:58:24.539072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb1a5322408'
down_revision = 'ac6ddac4a00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_plus_one', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bonus_plus_two', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bonus_extra_roll', sa.Boolean(), nullable=True))
        batch_op.drop_column('bonus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus', sa.VARCHAR(length=254), autoincrement=False, nullable=True))
        batch_op.drop_column('bonus_extra_roll')
        batch_op.drop_column('bonus_plus_two')
        batch_op.drop_column('bonus_plus_one')

    # ### end Alembic commands ###
