"""removed cell_number from Player

Revision ID: f80fc475bec7
Revises: cdb1a5322408
Create Date: 2025-03-03 23:01:11.063966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80fc475bec7'
down_revision = 'cdb1a5322408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('current_cell')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_cell', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
